version: "3.2"

services:
  nginx:
    image: etops/docker-nginx-https-redirect
    ports:
      - 80:80

  jupyter:
    image: etops/jupyter-datascience-notebook
    ports:
      - 443:8888

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
