version: "3.3"

services:
  nginx:
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
      
  jupyter:
    command: start-notebook.sh --NotebookApp.password='sha1:c1035137e1b3:297626588fbfc95cd08fde55d65d51a400d4f469' --NotebookApp.keyfile=/etc/letsencrypt/privkey.pem --NotebookApp.certfile=/etc/letsencrypt/fullchain.pem
    environment:
      NB_UID: "1000"
      NB_GID: "100"
      GRANT_SUDO: "yes"
      GEN_CERT: "no"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201