version: 2
jobs:
  build:
    working_directory: ~/etops/jupyter-datascience-notebook
    parallelism: 1
    environment:
      DOCKER_PRIVATE_REPO: etops
      IMAGE_NAME: jupyter-datascience-notebook
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 

      - run:
          name: Build application Docker image
          command: docker build --cache-from=$IMAGE_NAME -t $IMAGE_NAME .
          no_output_timeout: 30m

     # Login to docker hub and push the image
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $IMAGE_NAME $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest
